### ISSUE TITLE
Items can't be Touchables on Android

### ISSUE THREAD

**Issue by noway** [omulet/react-native-radial-menu#12]
works well on iOS, but onPress doesn't get triggered on Android. Any workaround?

```jsx
<RadialMenu onOpen={() => {}} onClose={() => {}}>
  <Text>ROOT</Text>
  <TouchableOpacity onSelect={() => {}} onPress={() => Alert.alert("test","test")}>A</TouchableOpacity>
  <TouchableOpacity onSelect={() => {}} onPress={() => Alert.alert("test","test")}>B</TouchableOpacity>
  <TouchableOpacity onSelect={() => {}} onPress={() => Alert.alert("test","test")}>C</TouchableOpacity>
  <TouchableOpacity onSelect={() => {}} onPress={() => Alert.alert("test","test")}>D</TouchableOpacity>
</RadialMenu>
```

**Comment by omulet** [comment]
The prop you want to use is `onSelect`. This method gets called when you release the menu button. So there is no event to trigger `onPress` and so, there's no reason to use a TouchableOpacity:
 ```jsx
<View onSelect={() => Alert.alert("test","test")} style={whatever}><Text>A</Text></View>
```
Hope this helps. Also, please check the Readme and the working example and make sure you're doing it right before submitting another issue.

**Comment by noway** [comment]
I want to use both, so that I can either select via dragging or open up the menu and click on individual one. Which I am able to set up easily on ios, but android doesn't seem to handle Touchable well with `tranfsorm`.
I ended up creating a overlay component above the buttons.
