### ISSUE TITLE
Images do not work in radial menu

### ISSUE THREAD

**Issue by Dantalion** [omulet/react-native-radial-menu#8]
Is there any way to use icons instead of text in the radial menu?
Adding Images with <Image> did not work, as the space for them gets reserved but they do not show up.

**Comment by omulet** [comment]
@Dantalion, I'm not quite sure what you mean by _the space for images gets reserved_. The plugin doesn't care what's rendered inside, so it's up to you what and how you style your elements. My suggestion is, try to display your image/icon without the use of any plugins first, then use with the plugin. If you're sure there is a bug, please submit a more specific issue, with exact steps to replicate, and some of your code snippets eventually.
Here's something for you to try out first:
```
npm install react-native-vector-icons -s
react-native link
```
then, in the example file
```javascript
import Icon from 'react-native-vector-icons/MaterialIcons'
//...
renderItems(count) {
  return ['home', 'info', 'settings', 'star', 'cake']
    .slice(0, count)
    .map((icon, i) => {
      return (
        <View style={styles.item} key={i} onSelect={ ()=>{} } >
          <Icon name={icon} size={30} color="#fff" />
        </View>
      );
    })
}
```
or replace `<Icon...` with `<Image source={require('./your-image-path')} />`
and here you go 😉
<img width="545" alt="screenshot 2017-11-24 09 08 55" src="https://user-images.githubusercontent.com/942632/33199095-7d7c53b0-d0f7-11e7-98e5-f72b42894b8a.png">

**Comment by Dantalion** [comment]
The error was on my side. It was an issue connected to react-native-vector-icons.
Thank you though.
